<?xml version="1.0" encoding="UTF-8"?>
<testng-results skipped="0" failed="1" ignored="0" total="3" passed="2">
  <reporter-output>
  </reporter-output>
  <suite name="Default suite" duration-ms="71" started-at="2018-05-08T16:10:33Z" finished-at="2018-05-08T16:10:33Z">
    <groups>
    </groups>
    <test name="Default test" duration-ms="71" started-at="2018-05-08T16:10:33Z" finished-at="2018-05-08T16:10:33Z">
      <class name="xyz.Login">
        <test-method status="PASS" signature="loginwithEmail()[pri:0, instance:xyz.Login@1810399e]" name="loginwithEmail" duration-ms="13" started-at="2018-05-08T16:10:33Z" finished-at="2018-05-08T16:10:33Z">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- loginwithEmail -->
        <test-method status="PASS" signature="loginwithFB()[pri:0, instance:xyz.Login@1810399e]" name="loginwithFB" duration-ms="3" started-at="2018-05-08T16:10:33Z" finished-at="2018-05-08T16:10:33Z">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- loginwithFB -->
        <test-method status="FAIL" signature="loginwithgoogle()[pri:0, instance:xyz.Login@1810399e]" name="loginwithgoogle" duration-ms="6" started-at="2018-05-08T16:10:33Z" finished-at="2018-05-08T16:10:33Z">
          <exception class="java.lang.AssertionError">
            <message>
              <![CDATA[expected [12] but found [11]]]>
            </message>
            <full-stacktrace>
              <![CDATA[java.lang.AssertionError: expected [12] but found [11]
at org.testng.Assert.fail(Assert.java:96)
at org.testng.Assert.failNotEquals(Assert.java:776)
at org.testng.Assert.assertEqualsImpl(Assert.java:137)
at org.testng.Assert.assertEquals(Assert.java:118)
at org.testng.Assert.assertEquals(Assert.java:652)
at org.testng.Assert.assertEquals(Assert.java:662)
at xyz.Login.loginwithgoogle(Login.java:22)
at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
at java.lang.reflect.Method.invoke(Method.java:497)
at org.testng.internal.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:124)
at org.testng.internal.Invoker.invokeMethod(Invoker.java:580)
at org.testng.internal.Invoker.invokeTestMethod(Invoker.java:716)
at org.testng.internal.Invoker.invokeTestMethods(Invoker.java:988)
at org.testng.internal.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:125)
at org.testng.internal.TestMethodWorker.run(TestMethodWorker.java:109)
at org.testng.TestRunner.privateRun(TestRunner.java:648)
at org.testng.TestRunner.run(TestRunner.java:505)
at org.testng.SuiteRunner.runTest(SuiteRunner.java:455)
at org.testng.SuiteRunner.runSequentially(SuiteRunner.java:450)
at org.testng.SuiteRunner.privateRun(SuiteRunner.java:415)
at org.testng.SuiteRunner.run(SuiteRunner.java:364)
at org.testng.SuiteRunnerWorker.runSuite(SuiteRunnerWorker.java:52)
at org.testng.SuiteRunnerWorker.run(SuiteRunnerWorker.java:84)
at org.testng.TestNG.runSuitesSequentially(TestNG.java:1208)
at org.testng.TestNG.runSuitesLocally(TestNG.java:1137)
at org.testng.TestNG.runSuites(TestNG.java:1049)
at org.testng.TestNG.run(TestNG.java:1017)
at org.testng.remote.AbstractRemoteTestNG.run(AbstractRemoteTestNG.java:114)
at org.testng.remote.RemoteTestNG.initAndRun(RemoteTestNG.java:251)
at org.testng.remote.RemoteTestNG.main(RemoteTestNG.java:77)
]]>
            </full-stacktrace>
          </exception> <!-- java.lang.AssertionError -->
          <reporter-output>
          </reporter-output>
        </test-method> <!-- loginwithgoogle -->
      </class> <!-- xyz.Login -->
    </test> <!-- Default test -->
  </suite> <!-- Default suite -->
</testng-results>
